### ISSUE TITLE
23 : Mortgaged property can be sold to the bank

### ISSUE THREAD

**Issue by Akinevz** [Lowkey-Awesome-Developers/Game_Logic_Prototype#10]
Once mortgaged, a property must have an option for being sold to the bank

>sold for one half of the property price shown on the card

**Comment by toninooleary** [comment]
Also stops rent from being taken with that property.

(Taken from user story/requirement 22)

**Comment by toninooleary** [comment]
Relates to #47

**Comment by Akinevz** [comment]
Solved by @toninooleary in 
https://github.com/Lowkey-Awesome-Developers/Game_Logic_Prototype/blob/master/src/com/lads/sw/board/squares/Property.java#L95
