### ISSUE TITLE
1 : Be able to roll the dice

### ISSUE THREAD

**Issue by toninooleary** [Lowkey-Awesome-Developers/Game_Logic_Prototype#20]
Have the ability to roll two 6 sided dice.

(Task created from requirement/user story 1)

**Comment by toninooleary** [comment]
<code> code notes test 
public void method(){
      test = test + 1;
}
</code>

**Comment by toninooleary** [comment]
'''
test = test + 1;
public void method(){
      test = test +1;
}
'''

**Comment by antgungre** [comment]
Fixed here
https://github.com/Lowkey-Awesome-Developers/Game_Logic_Prototype/blob/e94717b92b3a0e8bada4d07df06b2106f543b0e2/src/com/lads/sw/Dice.java#L5-L75
