### ISSUE TITLE
2 : Initialise each player to have 1,500 cash

### ISSUE THREAD

**Issue by toninooleary** [Lowkey-Awesome-Developers/Game_Logic_Prototype#22]
(Task created from requirement/user story 2)

**Comment by toninooleary** [comment]
Fix: 
https://github.com/Lowkey-Awesome-Developers/Game_Logic_Prototype/blob/69bea36d7679f9bd817d6fc4060ff185d468d6c5/src/com/lads/sw/player/Player.java#L73-L77

The above method is called in the Player Class constructor.

**Comment by antgungre** [comment]
Completed
