### ISSUE TITLE
6 : Create a system for managing board squares

### ISSUE THREAD

**Issue by toninooleary** [Lowkey-Awesome-Developers/Game_Logic_Prototype#27]
The board must have a system to manage all of the squares. 

The data loaded into the squares will be fixed on another issue specifically targeting loading data from .csv files to our game.

(Task created from requirement/user story 6)

**Comment by toninooleary** [comment]
Interface created for the board:

https://github.com/Lowkey-Awesome-Developers/Game_Logic_Prototype/blob/69bea36d7679f9bd817d6fc4060ff185d468d6c5/src/com/lads/sw/board/BoardSpec.java#L16-L27

Implementation of the interface using a board class:

https://github.com/Lowkey-Awesome-Developers/Game_Logic_Prototype/blob/69bea36d7679f9bd817d6fc4060ff185d468d6c5/src/com/lads/sw/board/Board.java#L8-L38

**Comment by Akinevz** [comment]
Management of board squares is implemented in Board
