### ISSUE TITLE
Taking card for player mechanism not implemented

### ISSUE THREAD

**Issue by antgungre** [Lowkey-Awesome-Developers/Game_Logic_Prototype#5]
- Player should be able to draw from deck
- Card effect should affect player
- Card should be placed at bottom of deck
- Draw card method, with each card effect having it's own method?

**Comment by Akinevz** [comment]
* drawing card from deck: https://github.com/Lowkey-Awesome-Developers/Game_Logic_Prototype/blob/master/src/com/lads/sw/effects/PickupCard.java#L19
* card taken from top of deck/ replaced at the bottom: https://github.com/Lowkey-Awesome-Developers/Game_Logic_Prototype/blob/master/src/com/lads/sw/board/Deck.java#L28
