### ISSUE TITLE
Portfolio must reference property specifics

### ISSUE THREAD

**Issue by antgungre** [Lowkey-Awesome-Developers/Game_Logic_Prototype#7]
-Portfolio objects must reference details such as mortaging of properties or how many houses or hotels are present on a property for each specific property
-This information is linked to changes in a player's current game currency.

**Comment by Akinevz** [comment]
Player portfolio is implemented in multiple parts in the player and board subpackages.

Player stores a reference to the set of properties owned by them.
Each property has a field referencing upgrade/purchase costs and a struct storing the current upgrade progress.
Functionality for mortgaging properties is implemented in the property class.
